### PR TITLE
Orchestration_update

### PR DESCRIPTION
**Pull request by Berchie-Sam**
I have removed some of the files and folders that I committed earlier.
This update includes what I have done under the experiment tracking and orchestration modules so far.

### CODE REVIEW

**Review by Silas-Asamoah — CHANGES_REQUESTED** [review]
THat's a lot of changes committed but you have quite a number of binary files that need to be removed and updated your ReadMe with a bit documentation from the various modules you have completed

**Comment by Silas-Asamoah** [comment]
@Berchie-Sam you still have a lot of binary files committed here

**Review by Silas-Asamoah — APPROVED** [review]
@Berchie-Sam I deleted a ton of things from here, check your gitignore and be sure you're not committing files from machine to git

**Comment by Berchie-Sam** [comment]
Okay I will. Thank you very much.

**Pull request merged**
